SELECT player_name, player_id
FROM player
WHERE player_name IN ('TAMIM IQBAL', 'MUSHFIQUR RAHIM','SHAKIB AL HASAN');


SELECT player_name, player_id
FROM player
WHERE player_id IN ( SELECT odi_player_rel
FROM odi
WHERE total_wicket>50);


SELECT player_name, player_id
FROM player
WHERE player_id IN ( SELECT odi_player_rel
FROM odi
WHERE player_option='PACE BOWLER');




SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY =50000
UNION ALL
SELECT P.PLAYER_NAME,P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.TEST_PLAYER_REL
FROM TEST T , T20 C
WHERE T.TOTAL_WICKET = C.TOTAL_WICKET
AND T.PLAYER_OPTION = 'PACE BOWLER');







SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY =100000
UNION ALL
SELECT P.PLAYER_NAME,P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.TEST_PLAYER_REL
FROM TEST T 
WHERE T.TOTAL_TEST_MATCH >50);



select PLAYER_NAME,PLAYER_ID
from player
WHERE PLAYER_SALARY = 500000
UNION
SELECT P.PLAYER_NAME, P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT o.ODI_PLAYER_REL
FROM ODI o
WHERE o.TOTAL_ODI_RUN >100);



SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 50000
INTERSECT
SELECT P.PLAYER_NAME, P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.T20_PLAYER_REL
FROM T20 T 
WHERE T.TOTAL_WICKET >10);


SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 50000
MINUS
SELECT P.PLAYER_NAME, P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.T20_PLAYER_REL
FROM T20 T 
WHERE T.TOTAL_WICKET >10);



SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 100000
UNION
SELECT P.PLAYER_NAME, P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.TEST_PLAYER_REL
FROM TEST T 
WHERE T.TOTAL_TEST_MATCH >30)
INTERSECT
SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 5000;


SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 100000
UNION
(SELECT P.PLAYER_NAME, P.PLAYER_ID
FROM PLAYER P
WHERE P.PLAYER_ID IN (SELECT T.TEST_PLAYER_REL
FROM TEST T 
WHERE T.TOTAL_TEST_MATCH >30)
INTERSECT
SELECT PLAYER_NAME, PLAYER_ID
FROM PLAYER
WHERE PLAYER_SALARY = 5000);

