SELECT P.PLAYER_NAME,P.PLAYER_ID, O.ODI_ID
	FROM PLAYER P  JOIN  ODI O
        ON P.PLAYER_ID=O.ODI_PLAYER_REL;



SELECT O.ODI_ID,T.TEST_ID
 FROM ODI O JOIN TEST T
 USING(TOTAL_WICKET);






SELECT O.ODI_ID,T.TEST_ID
 FROM ODI O JOIN TEST T
 USING(TOTAL_WICKET,PLAYER_OPTION,BOWLLING_TYPE);



 SELECT O.ODI_ID,T.TEST_ID
 FROM ODI O NATURAL JOIN TEST T;



SELECT AVERAGE_RUN,O.ODI_ID,T.TEST_ID
 FROM ODI O  NATURAL JOIN TEST T;



SELECT O.ODI_ID,T.T20_ID
 FROM ODI O   JOIN T20 T
ON O.ODI_PLAYER_REL=T.T20_PLAYER_REL;


SELECT O.ODI_ID,T.T20_ID
 FROM ODI O   JOIN T20 T
ON O.BOWLLING_TYPE=T.BOWLLING_TYPE
AND O.TOTAL_WICKET=T.TOTAL_WICKET;


SELECT O.ODI_ID,T.T20_ID
 FROM ODI O  CROSS JOIN T20 T;






SELECT P.PLAYER_NAME,P.PLAYER_ID,O.ODI_ID,O.TOTAL_ODI_MATCH
FROM PLAYER P LEFT OUTER JOIN ODI O
ON P.PLAYER_ID=O.ODI_PLAYER_REL;



SELECT P.PLAYER_NAME,P.PLAYER_ID,ODI_PLAYER_REL,O.ODI_ID,O.TOTAL_ODI_MATCH
FROM PLAYER P RIGHT OUTER JOIN ODI O
ON P.PLAYER_ID=O.ODI_PLAYER_REL;





SELECT O.ODI_ID,O.TOTAL_WICKET,M.TOTAL_ODI_MATCH
FROM ODI O JOIN ODI M
ON O.TOTAL_WICKET=M.TOTAL_ODI_MATCH;





SELECT O.ODI_ID,O.TOTAL_WICKET,M.TOTAL_ODI_MATCH
FROM ODI O LEFT OUTER JOIN ODI M
ON O.TOTAL_WICKET=M.TOTAL_ODI_MATCH;


