
INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2001,120,4000,32.00,'4-APR-2007',154,80,7,15,'LEFT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',120);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2002,129,3800,32.50,'4-APR-2007',121,85,3,14,'RIGHT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',121);


INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2003,130,3900,35.00,'4-APR-2007',134,78,7,17,'LEFT HAND BATSMAN',200,'10-5-30',
35.00,'LEFT ARM SPINNER',122);







INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2004,105,2100,31.00,'5-APR-2006',129,60,2,8,'RIGHT HAND BATSMAN',45,'10-3-25',
20.00,'OFF BREAK',123);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2005,135,1020,15.00,'16-AUG-2001',45,90,0,0,' PACE BOWLER',200,'10-5-40',
25.00,'RIGHT ARM PACER',124);






INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2006,20,1000,38.40,'5-MAR-2015',129,85,1,5,'LEFT HAND BATSMAN',2,'5-1-25',
10.00,'RIGHT ARM PACER',125);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2007,6,15,2.00,'17-JUN-2016',4,00,0,0,'PACE BOWLER',15,'10-6-45',
35.00,'LEFT ARM PACER',126);






INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2008,45,2000,31.10,'27-NOV-2012',100,75,1,5,'RIGHT HAND BATSMAN',15,'10-2-50',
15.00,'OFF BREAK',127);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2009,15,800,30.00,'9-JAN-2014',50,90,0,2,'RIGHT HAND BATSMAN',2,'5-2-29',
10.00,'LEG SPINNER',128);




INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2010,60,50,5.00,'17-JUL-2010',14,25,0,0,'PACE BOWLER',85,'10-5-36',
29.00,'RIGHT ARM PACER',129);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2011,20,30,3.00,'12-SEP-2014',5,0,0,0,'PACE BOWLER',25,'10-5-34',
22.00,'RIGHT ARM PACER',130);






INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2012,5,00,00.00,'4-FEB-2015',2,0,0,0,'SPINNER',5,'10-4-41',
20.00,'LEFT ARM SPINNER',131);




INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2013,6,4,00.00,'18-MAY-2015',2,00,0,0,'SPINNER',4,'10-2-50',
20.50,'LEG SPINNER',132);




INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL
) VALUES(2014,12,40,0.00,'4-APR-2015',10,0,0,0,'SPINNER',15,'10-4-43',
25.00,'LEFT ARM SPINNER',133);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2015,6,120,20.00,'17-JUN-2016',44,60,0,0,'RIGHT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',134);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2016,20,20,0.00,'4-APR-2014',10,00,0,0,'PACE BOWLER',22,'10-4-39',
30.00,'RIGHT ARM PACER',135);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2017,0,00,00.00,00,0,0,0,'PACE BOWLER',0,'NOT YET DEBUT',
0.00,'RIGHT ARM PACER',136);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2018,25,502,10.00,'2-DEC-2014',30,50,0,0,'SPINNER',31,'10-5-38',
30.00,'OFF BREAK',137);



INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL
) VALUES(2019,8,200,25.00,'14-AUG-2013',47,54,0,0,'LEFT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',138);




INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2020,0,00,00.00,0,0,0,0,'PACE BOWLER',0,'NOT YET DEBUT',
0.00,'RIGHT ARM PACER',139);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2021,0,00,0.00,0,00,0,0,'RIGHT HAND BATSMAN',0,'NOT YET DEBUT',
0.00,'NOT YET DEBUT',140);






INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2022,45,1500,31.50,'19-NOV-2009',100,65,1,7,'LEFT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',141);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2023,31,800,27.00,'24-JAN-2013',125,70,2,4,'RIGHT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',142);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2024,80,400,10.00,'20-APR-2006',54,40,0,1,'SPINNER',201,'10-5-41',
25.14,'LEFT ARM SPINNER',143);




INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2025,15,120,18.00,'4-APR-2012',20,45,0,0,'SPINNER',12,'10-3-48',
21.00,'LEFT ARM SPINNER',144);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL 
) VALUES(2026,150,3990,31.00,'3-FEB-2006',105,61,2,8,'RIGHT HAND BATSMAN',0,'NOT YET BOWLING',
0.00,'NOT YET BOWLING',145);





INSERT INTO ODI  ( 
ODI_ID ,
TOTAL_ODI_MATCH ,
TOTAL_ODI_RUN ,
AVERAGE_RUN ,
DATE_DEBUT  ,
BEST_SCORE ,
STRIKE_RATE ,
NUMBER_HUNDRED ,
NUMBER_FIFTY ,
PLAYER_OPTION  ,
TOTAL_WICKET ,
BEST_BOWLLING ,
BOWLLING_AVERAGE ,
BOWLLING_TYPE ,
ODI_PLAYER_REL
) VALUES(2027,11,100,12.00,'14-JUN-2013',38,85,0,0,'RIGHT HAND BATSMAN',8,'10-3-50',
15.00,'RIGHT ARM PACER',146);


