DROP TABLE T20;
DROP TABLE TEST;
DROP TABLE ODI;
DROP TABLE PLAYER;
DROP TABLE COACHING_STAFF;
DROP TABLE BOARD;




CREATE TABLE BOARD
( BOARD_ID NUMBER(5) NOT NULL,
 BOARD_NAME VARCHAR(50),
 BOARD_EMAIL  VARCHAR(50),
 COUNTRY_NAME VARCHAR(50),
 PRIMARY KEY  (BOARD_ID)
 );



 CREATE TABLE PLAYER
( 
 PLAYER_ID NUMBER(10) NOT NULL,
 PLAYER_NAME VARCHAR(50),
 PLAYER_DATE_BIRTH DATE,
 PLAYER_OPTION VARCHAR(30),
 PLAYER_PHONENUMBER NUMBER(11),
 PLAYER_EMAIL  VARCHAR(50),
 PLAYER_DISTRICT VARCHAR(50),
 PLAYER_UPAZILLA VARCHAR(50),
 PLAYER_SALARY   NUMBER(6) NOT NULL,
 PLAYER_HEIGHT NUMBER(4,2),
 PLAYER_BOARD_REL NUMBER(5) NOT NULL,
 PRIMARY KEY (PLAYER_ID),
 FOREIGN KEY (PLAYER_BOARD_REL) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE
);


CREATE TABLE COACHING_STAFF
(
COACHING_ID NUMBER(5) NOT NULL,
STAFF_NAME VARCHAR(30),
STAFF_RANK VARCHAR(30),
STAFF_EMAIL VARCHAR(50),
STAFF_PHONENUMBER NUMBER(15),
STAFF_SALARY NUMBER(5),
STAFF_DATE_AGREEMENT DATE,
STAFF_BOARD_REL NUMBER(5) NOT NULL,
PRIMARY KEY (COACHING_ID),
FOREIGN KEY (STAFF_BOARD_REL) REFERENCES BOARD(BOARD_ID) ON DELETE CASCADE
);

CREATE TABLE ODI
(
ODI_ID NUMBER(5) NOT NULL,
TOTAL_ODI_MATCH NUMBER(3),
TOTAL_ODI_RUN NUMBER(5),
AVERAGE_RUN NUMBER(5,3),
DATE_DEBUT  DATE,
BEST_SCORE NUMBER(3),
STRIKE_RATE NUMBER(5,2),
NUMBER_HUNDRED NUMBER(3),
NUMBER_FIFTY NUMBER(3),
PLAYER_OPTION  VARCHAR(100),
TOTAL_WICKET NUMBER(3),
BEST_BOWLLING VARCHAR(50),
BOWLLING_AVERAGE NUMBER(5,2),
BOWLLING_TYPE VARCHAR(20),
ODI_PLAYER_REL NUMBER(5) NOT NULL,
PRIMARY KEY (ODI_ID),
FOREIGN KEY (ODI_PLAYER_REL) REFERENCES PLAYER(PLAYER_ID) ON DELETE CASCADE
);




CREATE TABLE TEST
(
TEST_ID NUMBER(5) NOT NULL,
TOTAL_TEST_MATCH NUMBER(3),
TOTAL_TEST_INNINGS NUMBER(3),
TOTAL_TEST_RUN NUMBER(5),
AVERAGE_RUN NUMBER(5,3),
ICC_RANKING NUMBER(3),
DATE_DEBUT  DATE,
BEST_SCORE NUMBER(3),
STRIKE_RATE NUMBER(5,2),
NUMBER_HUNDRED NUMBER(3),
NUMBER_FIFTY NUMBER(3),
PLAYER_OPTION  VARCHAR(100),
TOTAL_WICKET NUMBER(3),
BEST_BOWLLING VARCHAR(50),
BOWLLING_AVERAGE NUMBER(5,2),
BOWLLING_TYPE VARCHAR(20),
TEST_PLAYER_REL NUMBER(5) NOT NULL,
PRIMARY KEY (TEST_ID),
FOREIGN KEY (TEST_PLAYER_REL) REFERENCES PLAYER(PLAYER_ID) ON DELETE CASCADE
);



  CREATE TABLE T20
(
T20_ID NUMBER(5) NOT NULL,
TOTAL_T20_MATCH NUMBER(3),
TOTAL_T20_INNINGS NUMBER(3),
TOTAL_T20_RUN NUMBER(5),
AVERAGE_RUN NUMBER(5,3),
DATE_DEBUT  DATE,
BEST_SCORE NUMBER(3),
STRIKE_RATE NUMBER(5,2),
NUMBER_HUNDRED NUMBER(3),
NUMBER_FIFTY NUMBER(3),
PLAYER_OPTION VARCHAR(100),
TOTAL_WICKET NUMBER(3),
BEST_BOWLLING VARCHAR(50),
BOWLLING_AVERAGE NUMBER(5,2),
BOWLLING_TYPE VARCHAR(20),
T20_PLAYER_REL NUMBER(5) NOT NULL,
PRIMARY KEY (T20_ID),
FOREIGN KEY (T20_PLAYER_REL) REFERENCES PLAYER(PLAYER_ID) ON DELETE CASCADE
);


