
INSERT INTO TEST (
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5001,42,80,3118,39.46,51,'1-JAN-2008',206,55.40,7,18,'LEFT HAND BATSMAN',0,'NOT YET BOWLLING',0,'NOT YET BOWLLING',120);

INSERT INTO TEST (
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5002,48,88,2650,32.31,42,'26-MAY-2005',200,46.48,3,15,'RIGHT HAND BATSMAN',0,'NOT YET BOWLLING',0,'NOT YET BOWLLING',121);

INSERT INTO TEST (
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5003,42,78,2823,39.76,19,'18-MAY-2007',144,61.14,3,19,'LEFT HAND BATSMAN',147,'7-36',33.31,'LEFT ARM SPINNER',122);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL)VALUES(5004,27,50,1506,31.37,62,'9-JUL-2009',115,51.36,1,12,'RIGHT HAND BATSMAN',37,'5-51',45.40,'OFF BREAK',123);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5005,36,67,797,12.85,0,'8-NOV-2001',79,67.20,0,3,'PACE BOWLER',78,'4-60',41.52,'RIGHT ARM PACER',124);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5006,3,5,107,21.40,79,'28-APR-2015',37,60.79,0,0,'LEFT HAND BATSMAN',1,'1-45',115.00,'RIGHT ARM PACER',125);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5007,2,2,3,3.00,0,'21-JUL-2015',3,23.07,0,0,'PACE BOWLER',4,'4-37',14.50,'LEFT ARM PACER',126);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5008,17,30,1456,56.00,31,'8-MAR-2013',181,54.83,4,9,'LEFT HAND BATSMAN',1,'1-10',192.0,'LEFT ARM SPINNER',138);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5009,3,3,97,32.33,105,'10-JUN-2015',50,61.39,0,1,'RIGHT HAND BATSMAN',0,'NOT YET BOWLLING',0,'NOT YET BOWLLING',134);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5010,6,9,13,4.33,0,'25-OCT-2015',7,14.77,0,0,'SPINNER',16,'5-96',30.81,'LEG SPINNER',132);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5011,17,28,971,37.34,60,'21-OCT-2011',100,55.90,1,6,'RIGHT HAND BATSMAN',8,'3-130',51.62,'OFF BREAK',127);



INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5012,0,0,0,0,0,0,0,0,0,'RIGHT HAND BATSMAN',0,'NOT YET DEBUTANT',0,'NOT YET BOWLLING',128);



INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5013,23,40,197,8.95,0,'9-JUL-2013',45,43.00,0,0,'PACE BOWLER',32,'5-166',75.90,'RIGHT ARM PACER',129);



INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5014,0,0,0,0,0,0,0,0,0,'PACE BOWLER',0,'NOT YET DEBUTANT',0,'RIGHT ARM PACER',130);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5015,9,16,137,11.41,0,'5-SEP-2014',32,47.07,0,0,'SPINNER',36,'8-39',33.94,'LEFT ARM SPINNER',131);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5016,0,0,0,0,0,0,0,0,0,'SPINNER',0,'NOT YET DEBUTANT',0,'LEFT ARM SPINNER',133);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL)VALUES(5017,6,9,68,22.66,0,'21-OCT-2013',32,66.01,0,0,'PACE BOWLER',6,'3-80',76.66,'RIGHT ARM PACER',135);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5018,9,17,99,9.00,0,'27-MAY-2010',33,48.76,0,0,'PACE BOWLER',25,'6-71',39.68,'RIGHT ARM PACER',136);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5019,10,18,325,21.66,200,'13-NOV-2012',101,61.43,1,0,'SPINNER',38,'6-74',42.07,'OFF BREAK',137);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5020,5,6,57,11.40,0,'28-APR-2015',25,70.37,0,0,'PACE BOWLER',5,'2-23',57.60,'RIGHT ARM PACER',139);

INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5021,7,13,213,21.30,0,'5-SEP-2014',50,54.47,0,1,'RITHT HAND BATSMAN',8,'2-66',59.12,'OFF BREAK',140);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5022,24,46,1252,27.82,55,'19-NOV-2008',150,47.820,1,5,'LEFT HAND BATSMAN',0,'NOT YET BOWLLING',0,'NOT YET BOWLLING',141);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5023,4,8,73,9.12,106,'8-MAR-2013',22,33.18,0,0,'RIGHT HAND BATSMAN',0,'NOT YET BOWLLING',0,'NOT YET BOWLLING',142);


INSERT INTO TEST(
TEST_ID,
TOTAL_TEST_MATCH,
TOTAL_TEST_INNINGS,
TOTAL_TEST_RUN,
AVERAGE_RUN,
ICC_RANKING,
DATE_DEBUT,
BEST_SCORE,
STRIKE_RATE,
NUMBER_HUNDRED,
NUMBER_FIFTY,
PLAYER_OPTION,
TOTAL_WICKET,
BEST_BOWLLING,
BOWLLING_AVERAGE,
BOWLLING_TYPE,
TEST_PLAYER_REL
)VALUES(5024,12,18,245,17.50,0,'16-APR-2006',43,65.33,0,0,'SPINNER',23,'3-93',67.39,'LEFT ARM SPINNER',143);

commit;






